---
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
- name: Create ~/.ssh/keys
  file:
   path: "/home/{{ privateuser }}/.ssh/keys"
   state: directory
   recurse: true
   owner: "{{ privateuser }}"
   group: "{{ privateuser }}"
   mode: '0700'

- name: Set authorized key
  authorized_key:
   user: "{{ privateuser }}"
   state: present
   key: "{{ lookup('file', 'files/yasu-homepc-ed25519.pub') }}"
