---
- name: Create ~/.ssh/keys
  file:
   path: "/home/{{ privateuser }}/.ssh/keys"
   state: directory
   recurse: true
   owner: "{{ privateuser }}"
   group: "{{ privateuser }}"
   mode: '0700'

- name: Set authorized key
  authorized_key:
   user: "{{ privateuser }}"
   state: present
   key: "{{ lookup('file', 'files/yasu-homepc-ed25519.pub') }}"

#   - name: Create host rsa key
#     openssh_keypair:
#      path: /etc/ssh/ssh_host_rsa_key
#      type: rsa
#      size: 3072

#   - name: Create host ecdsa key
#     openssh_keypair:
#      path: /etc/ssh/ssh_host_ecdsa_key
#      type: ecdsa
#      size: 256

- name: Create host ed25519 key
  openssh_keypair:
   path: /etc/ssh/ssh_host_ed25519_key
   type: ed25519
