---
- name: Find out what is the currently active policy
  command: "update-crypto-policies --show"
  register: crypto_policies_active
  check_mode: false
  changed_when: false
  failed_when: false

# update-policy when changeds
